toggleservice:
  image: sd1pgo01lx.saksdirect.com/toggle-service:<version>
  restart: always
  ports:
    - "9860:9860"
  environment:
    - JAVA_OPTS=-Xms1g -Xmx1g {{key "newrelic"}}
    - CONSUL_HOST={{key "consul_host"}}
    - ENV={{key "env"}}
  log_driver: syslog
  log_opt:
    syslog-address: <logstash_url>
    syslog-tag: <banner>-<env>-<service>
  labels:
    - "com.joyent.package=<triton_package>"
  command: /opt/containerbuddy/containerbuddy -config file:///opt/containerbuddy/config.json  /opt/toggle-service-0.1/bin/toggle-service -Dhttp.port=9860 -Dpidfile.path=/dev/null -Dconfig.file=/opt/toggle-service-0.1/conf/toggle-application.conf -Dlogger.file=/opt/toggle-service-0.1/conf/docker-logger.xml
