platform: linux

inputs:
- name: toggle-service-repo
- name: aws-ref-arch

run:
  dir: toggle-service-repo/infrastructure/terraform
  path: bash
  args:
    - -exc
    - |
      source DEV.sh
      commit_sha=$(git rev-parse --short HEAD)
      ./scripts/deploy.sh $commit_sha
