platform: linux

inputs:
- name: toggle-service-repo
- name: aws-ref-arch
- name: version

run:
  dir: toggle-service-repo/infrastructure/terraform
  path: bash
  args:
    - -exc
    - |
      source $TF_ENV.sh
      tag=$(cat ../../../version/number)
      ./scripts/deploy.sh $tag
